config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"

  resources :quotes do
    resources :line_item_dates, except: [:index] do
      resources :line_items, except: [:index, :show]
    end
  end
  resources :pages, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :line_item_date

  validates :name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, presence: true, numericality: { greater_than: 0 }

  delegate :quote, to: :line_item_date

  # equivalent to
  # line_item.line_item_date.quote
  # line_item.quote
end

app/models/line_item_date.rb
class LineItemDate < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :quote

  validates :date, presence: true, uniqueness: { scope: :quote_id }

  scope :ordered, -> { order(date: :asc) }

  def previous_date
    quote.line_item_dates.ordered.where("date < ?", date).last
  end
end

app/models/quote.rb
class Quote < ApplicationRecord
  has_many :line_item_dates, dependent: :destroy
  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  belongs_to :company
  # after_create_commit -> { broadcast_prepend_to "quotes", partial: "quotes/quote", locals: { quote: self }, target: "quotes" }

  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }

  # Those three callbacks are equivalent to the following single line
  broadcasts_to ->(quote) { [quote.company, "quotes"] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  belongs_to :company

  def name
    email.split("@").first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end

  helper_method :current_company
end

app/controllers/line_item_dates_controller.rb
class LineItemDatesController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date, except: %i[new create]

  def new
    @line_item_date = @quote.line_item_dates.build
  end

  def create
    @line_item_date = @quote.line_item_dates.build(line_item_date_params)

    if @line_item_date.save
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), notice: "Date was successfully created."}
        format.turbo_stream { flash.now[:notice] = "Date was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @line_item_date.update(line_item_date_params)
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), notice: "Date was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Date was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show; end

  def destroy
    @line_item_date.destroy

    respond_to do |format|
      format.html { redirect_to quote_path(@quote), notice: "Date was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Date was successfully destroyed." }
    end
  end

  private

    def set_line_item_date
      @line_item_date = @quote.line_item_dates.find(params[:id])
    end

    def line_item_date_params
      params.require(:line_item_date).permit(:date)
    end

    def set_quote
      @quote = current_company.quotes.find(params[:quote_id])
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date
  before_action :set_line_item, except: %i[create new]

  def new
    @line_item = @line_item_date.line_items.build
  end

  def create
    @line_item = @line_item_date.line_items.build(line_item_params)

    if @line_item.save
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), notice: "Item was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Item was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @line_item.update(line_item_params)
      respond_to do |format|
        format.html { redirect_to quote_path(@quote), notice: "Item was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Item was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to quote_path(@quote), notice: "Date was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Date was successfully destroyed." }
    end
  end

  private

    def line_item_params
      params.require(:line_item).permit(:name, :description, :quantity, :unit_price)
    end

    def set_quote
      @quote = current_company.quotes.find(params[:quote_id])
    end

    def set_line_item_date
      @line_item_date = @quote.line_item_dates.find(params[:line_item_date_id])
    end

    def set_line_item
      @line_item = @line_item_date.line_items.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  def index
    @quotes = current_company.quotes.ordered
  end

  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)

    if @quote.save
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @quote.update(quote_params)
      respond_to do |format|
        format.html { redirect_to quotes_path, notice: "Quote was successfully updated." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
    end
  end

  private

    def set_quote
      @quote = current_company.quotes.find(params[:id])
    end

    def quote_params
      params.require(:quote).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end

  def form_error_notification(object)
    if object.errors.any?
      tag.div class: "error-message" do
        object.errors.full_messages.to_sentence.capitalize
      end
    end
  end

  def nested_dom_id(*args)
    args.map { |arg| arg.respond_to?(:to_key) ? dom_id(arg) : arg }.join("_")
  end
end

app/views/layouts/_flash.html.haml
- flash.each do |flash_type, message|
  .flash__message{"data-controller": "removals", "data-action": "animationend->removals#remove"}
    = message

app/views/layouts/_navbar.html.haml
%header.navbar
  - if user_signed_in?
    .navbar__brand
      = current_company.name
    .navbar__name
      = current_user.name
    = button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn--dark"
  - else
    = link_to "Sign in", new_user_session_path, class: "btn btn--dark navbar__right"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title QuoteEditor
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    = render "layouts/navbar"

    .flash#flash
      = render "layouts/flash"

    = yield

app/views/line_item_dates/_form.html.haml
= turbo_frame_tag dom_id(quote) do
  = simple_form_for [quote, line_item_date], html: { class: "form line-item-date" } do |f|
    = form_error_notification(line_item_date)

    = f.input :date, html5: true, input_html: { autofocus: true }
    = link_to "Cancel",
              line_item_date.valid? ? [quote, line_item_date] : quote,
              class: "btn btn--light"
    = f.submit class: "btn btn--secondary"

app/views/line_item_dates/_line_item_date.html.haml
= turbo_frame_tag line_item_date do
  .line-item-date
    = turbo_frame_tag dom_id(line_item_date, :edit) do
      .line-item-date__header
        %h2.line-item-date__title= l(line_item_date.date, format: :long)

        .line-item-date__actions
          = button_to "Delete",
                      [quote, line_item_date],
                      method: :delete,
                      form: { data: { turbo_confirm: "Are you sure?" } },
                      class: "btn btn--light"

          = link_to "Edit",
                    [:edit, quote, line_item_date],
                    class: "btn btn--light"

    .line-item-date__body
      .line-item.line-item--header
        .line-item__name Article
        .line-item__quantity Quantity
        .line-item__price Price
        .line-item__actions

      // FRAME TO ITEMS LIST
      = turbo_frame_tag nested_dom_id(line_item_date, "line_items") do
        = render line_item_date.line_items, quote: quote, line_item_date: line_item_date

      // frame for new items
      = turbo_frame_tag nested_dom_id(line_item_date, LineItem.new)

      .line-item-date__footer
        = link_to "Add item",
                  [:new, quote, line_item_date, :line_item],
                  data: { turbo_frame: nested_dom_id(line_item_date, LineItem.new) },
                  class: "btn btn--primary"

app/views/line_item_dates/create.turbo_stream.erb
<%# Step 1: remove the form from the Quotes#index page %>
<%= turbo_stream.update LineItemDate.new, "" %>

<%# Step 2: add the date at the right place %>
<% if previous_date = @line_item_date.previous_date %>
  <%= turbo_stream.after previous_date do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "line_item_dates" do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/line_item_dates/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item_date %>
<%= render_turbo_stream_flash_messages %>

app/views/line_item_dates/edit.html.haml
%main.container
  = link_to sanitize("&larr; Back to quote"), quote_path(quote_id: @quote) # estaba corrigiendo esto
  .header
    %h1 Edit date

  = turbo_frame_tag dom_id(@line_item_date, :edit) do
    = render "form", quote: @quote, line_item_date: @line_item_date

app/views/line_item_dates/new.html.haml
%main.container
  = link_to sanitize("&larr; Back to quote"), quote_path(@quote)
  %header.header
    %h1 New date

  = turbo_frame_tag @line_item_date do
    = render "form", quote: @quote, line_item_date: @line_item_date

app/views/line_item_dates/show.html.haml
%main.container
  = link_to sanitize("&larr; Back to quote"), quote_path(quote_id: @quote)
  .header
    %h1 Date

  = turbo_frame_tag dom_id(@line_item_date) do
    = turbo_frame_tag dom_id(@quote) do
      .line-item-date__header
        %h2.line-item-date__title= l(@line_item_date.date, format: :long)

        .line-item-date__actions
          = button_to "Delete",
                      [@quote, @line_item_date],
                      method: :delete,
                      form: { data: { turbo_confirm: "Are you sure?" } },
                      class: "btn btn--light"

          = link_to "Edit",
                    [:edit, @quote, @line_item_date],
                    class: "btn btn--light"

app/views/line_item_dates/update.turbo_stream.erb
<%# Step 1: remove the form %>
<%= turbo_stream.remove @line_item_date %>

<%# Step 2: insert the updated date at the correct position %>
<% if previous_date = @line_item_date.previous_date %>
  <%= turbo_stream.after previous_date do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "line_item_dates" do %>
    <%= render @line_item_date, quote: @quote %>
  <% end %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/line_items/_form.html.haml
= simple_form_for [quote, line_item_date, line_item], html: { class: "form line-item line-item--form" } do |f|
  = form_error_notification(line_item)

  = f.input :name,
            wrapper_html: { class: "line-item__name" },
            input_html: { autofocus: true }
  = f.input :quantity,
            wrapper_html: { class: "line-item__quantity" }
  = f.input :unit_price,
            wrapper_html: { class: "line-item__price" }
  = f.input :description,
            wrapper_html: { class: "line-item__description" }

  .line-item__actions
    = link_to "Cancel", quote_path(quote), class: "btn btn--light"
    = f.submit class: "btn btn--secondary"

app/views/line_items/_line_item.html.haml
= turbo_frame_tag line_item do
  .line-item
    .line-item__name
      = line_item.name
      .line-item__description
        = simple_format line_item.description

    .line-item__quantity-price
      = line_item.quantity
      &times;
      = number_to_currency line_item.unit_price

    .line-item__quantity
      = line_item.quantity

    .line-item__price
      = number_to_currency line_item.unit_price

    .line-item__actions
      = button_to "Delete",
                  [quote, line_item_date, line_item],
                  method: :delete,
                  class: "btn btn--light"
      = link_to "Edit",
                [:edit, quote, line_item_date, line_item],
                class: "btn btn--light"

app/views/line_items/create.turbo_stream.erb
<%# Step 1: empty the Turbo Frame containing the form %>
<%= turbo_stream.update nested_dom_id(@line_item_date, LineItem.new), "" %>

<%# Step 2: append the created line item to the list %>
<%= turbo_stream.append nested_dom_id(@line_item_date, "line_items") do %>
  <%= render @line_item, quote: @quote, line_item_date: @line_item_date %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item %>
<%= render_turbo_stream_flash_messages %>

app/views/line_items/edit.html.haml
%main.container
  = link_to sanitize("&larr; Back to quote"), quote_path(@quote)
  %header.header
    %h1 Edit Item

  = turbo_frame_tag @line_item do
    = render "form",
              quote: @quote,
              line_item_date: @line_item_date,
              line_item: @line_item

app/views/line_items/new.html.haml
%main.container
  = link_to sanitize("&larr; Back to quote"), quote_path(@quote)
  .header
    %h1 New item for #{l(@line_item_date.date, format: :long)}

  = turbo_frame_tag nested_dom_id(@line_item_date, LineItem.new) do
    = render "form",
              quote: @quote,
              line_item_date: @line_item_date,
              line_item: @line_item

app/views/line_items/update.turbo_stream.erb
<%= turbo_stream.replace @line_item do %>
  <%= render @line_item, quote: @quote, line_item_date: @line_item_date %>
<% end %>

<%= render_turbo_stream_flash_messages %>

app/views/pages/index.html.haml
%main.container
  %h1 Quote editor
  %p A blazing fast quote editor built with Hotwire

  - if user_signed_in?
    = link_to "View quotes", quotes_path, class: "btn btn--dark"
  - else
    - link_to "Sign_in", new_user_session_path, class: "btn btn--dark"

app/views/quotes/_empty_state.html.haml
.empty-state.empty-state--only-child
  %p.empty-state__text You don't have any quotes yet!
  = link_to "Add quote", new_quote_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Quote.new) }

app/views/quotes/_form.html.haml
= simple_form_for quote, html: { class: 'quote form' } do |f|
  = form_error_notification(quote)

  = f.input :name, input_html: { autofocus: true }
  = link_to "Cancel", quotes_path, class: "btn btn--light"
  = f.submit class: "btn btn--secondary"

app/views/quotes/_quote.html.haml
= turbo_frame_tag quote do
  .quote
    = link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" }
    .quote__actions
      = button_to "Delete", quote_path(quote), method: :delete, class: "btn btn--light", form: { data: { turbo_frame: "_top" } }
      = link_to "Edit", edit_quote_path(quote), class: "btn btn--light"

app/views/quotes/create.turbo_stream.erb
<%
=begin%>
 <%= turbo_stream.prepend "quotes", partial: "quotes/quote", locals: { quote: @quote } %> 
<%
=end%>

<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>

app/views/quotes/edit.html.haml
%main.container
  = link_to sanitize("&larr; Back to quotes"), quotes_path
  %header.header
    %h1 Edit quote

  = turbo_frame_tag @quote do
    = render "form", quote: @quote

app/views/quotes/index.html.haml
= turbo_stream_from current_company, "quotes"

%main.container
  = turbo_frame_tag "first_turbo_frame" do
    %header.header
      %h1 Quotes
      = link_to "New quote", new_quote_path, class: "btn btn--primary", data: { "turbo-frame": dom_id(Quote.new) }

  = turbo_frame_tag dom_id(Quote.new)

  = turbo_frame_tag 'quotes' do
    = render "quotes/empty_state"
    = render @quotes

app/views/quotes/new.html.haml
%main.container
  = link_to sanitize("&larr; Back to quotes"), quotes_path
  = turbo_frame_tag "first_turbo_frame" do
    %header.header
      %h1 New quote

  = turbo_frame_tag dom_id(Quote.new) do
    = render "form", quote: @quote

app/views/quotes/show.html.haml
%main.container
  = link_to sanitize("&larr; Back to quotes"), quotes_path
  .header
    %h1= @quote.name
    = link_to "New date",
              new_quote_line_item_date_path(@quote),
              class: "btn btn--primary",
              data: { "turbo-frame": dom_id(LineItemDate.new) }
  %hr
  = turbo_frame_tag LineItemDate.new

  = turbo_frame_tag "line_item_dates" do
    = render @line_item_dates, quote: @quote

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>